@host = http://localhost:5000

###
GET {{host}}/api/todo-items
Accept: application/json

###
GET {{host}}/api/todo-items/1
Accept: application/json

###
POST {{host}}/api/todo-items
Content-Type: application/json

"Buy Coffee Beans"

###
PUT {{host}}/api/todo-items/1
Content-Type: application/json

"Updated: Feed the cat"

###
DELETE {{host}}/api/todo-items/1

###
POST {{host}}/api/todo-items
Content-Type: application/json

{
    "description": "Go to eat",
    "assignedTo": "Me"  
}

###
PUT {{host}}/api/todo-items/1
Content-Type: application/json

{
    "description": "Go to the supermarket",
    "assignedTo": "Me"  
}

###
POST {{host}}/tot
Content-Type: application/json

{
    "name":"Gershon",
    "email":"gershon@gmail.com",
    "department":"RI"
}


###
GET {{host}}/api/employee/all
Accept: application/json

###
POST {{host}}/api/employee/add
Content-Type: application/json

{
    "name":"Test",
    "email":"test@gmail.com",
    "department":"GOOGLE"
}

###
PUT {{host}}/api/employee/update/1
Content-Type: application/json

{
    "name":"Eran",
    "email":"eran.weiser@gmail.com",
    "department":"R&D"
}

###
PUT {{host}}/api/employee/updateq/2?name=Yossi&email=eran@algotec.co.il

###
DELETE {{host}}/api/employee/delete/4


###
GET {{host}}/api/todo-items
Accept: application/json

###
GET {{host}}/api/todo-items/0
Accept: application/json

###
POST {{host}}/api/todo-items
Content-Type: application/json

"Watch TV"

###
PUT {{host}}/api/todo-items/2
Content-Type: application/json

"Watch Netflix"

###
DELETE {{host}}/api/todo-items/2

###
GET {{host}}/api/todo-items/sorted?sortOrder=asc
Accept: application/json

###
# ==============================================================================
GET {{host}}/api/todo-items-advanced
Accept: application/json

###
GET {{host}}/api/todo-items-advanced/0
Accept: application/json

###
POST {{host}}/api/todo-items-advanced
Content-Type: application/json

{
    "description": "Watch TV",
    "assignedTo": "Me"
}

###
POST {{host}}/api/todo-items-advanced
Content-Type: application/json

{
    "description": "x",
    "assignedTo": "Me"
}

###
PUT {{host}}/api/todo-items-advanced/2
Content-Type: application/json

{
    "description": "Watch Netfix",
    "assignedTo": "Me"
}

###
DELETE {{host}}/api/todo-items-advanced/2